#ifndef GLOBAL
#define GLOBAL

enum STATE{AKTIV, INAKTIV};
enum BEGRENZUNGSTYP{LINKS_LINKS, LINKS_RECHTS, RECHTS_RECHTS, RECHTS_LINKS, GERADESEITE};
enum STRECKENTYP{GERADE, LINKSKURVE, RECHTSKURVE};
struct CollisionCheckPoint
{
    qreal x, y;
    STATE state = INAKTIV;
};
#endif // GLOBAL

